// JENIS KONTEN PER MENU — satu sumber data untuk UI (setting otomatis) dan prompt (panduan khusus).
// def : setting storyboard (adegan, shot, durasi, ratio, char, voice, style). style boleh kunci ST (cine/doc/pixar/ugc/drama/tl/asmr) atau teks opsi.
// ex  : isi "Opsi Lanjutan" (nama field → nilai opsi). guide : instruksi tambahan untuk AI. ph : contoh ide.
const V = (id, name, desc, def, ex, guide, ph) => ({ id, name, desc, def, ex, guide, ph });

module.exports = {
    'video-iklan': [
        V('produk', 'Iklan Produk', 'Premium & sinematik, produk jadi bintang', { adegan: '2', shot: '4', durasi: '10s', style: 'cine', voice: 'Voice-Over Narrator' },
            { 'Gaya iklan': 'Sinematik premium', 'Tujuan iklan': 'Penjualan langsung', 'Struktur cerita': 'Demo produk', 'CTA penutup': 'Beli sekarang' },
            'Fokus pada produk: close-up tekstur, material, detail kemasan, dan hero shot di akhir. Pencahayaan studio mewah, gerak kamera halus. Produk selalu terlihat jelas di setiap adegan.',
            'Contoh: Parfum botol kaca elegan, aroma kayu cendana, target pekerja muda'),
        V('umkm', 'Iklan UMKM / Produk Lokal', 'Hangat, otentik, dekat dengan pembeli', { adegan: '3', shot: '3', durasi: '10s', ratio: '9:16', style: 'ugc', voice: 'Character + Narrator' },
            { 'Gaya iklan': 'Lifestyle', 'Tujuan iklan': 'Penjualan langsung', 'Struktur cerita': 'Testimoni', 'CTA penutup': 'Chat / DM' },
            'Gaya jujur dan membumi ala pemilik usaha lokal: dapur/workshop sederhana, proses pembuatan, wajah pemilik, pelanggan setia. Bahasa santai dan akrab, tonjolkan kualitas buatan tangan, bahan lokal, dan harga terjangkau. Jangan terlalu mewah.',
            'Contoh: Keripik singkong buatan ibu rumahan, renyah, bumbu balado, tanpa pengawet'),
        V('promo', 'Promo & Diskon', 'Hard sell dengan urgensi dan harga', { adegan: '2', shot: '4', durasi: '8s', ratio: '9:16', style: 'cine', voice: 'Voice-Over Narrator' },
            { 'Gaya iklan': 'Hard sell promo', 'Tujuan iklan': 'Promo / diskon', 'Struktur cerita': 'Problem → Solution', 'CTA penutup': 'Beli sekarang' },
            'Ritme cepat dan energik. Hook 2 detik pertama harus langsung menyebut penawaran. Sertakan elemen urgensi (waktu terbatas, stok terbatas) dan tampilan harga/diskon sebagai teks di layar. Penutup wajib berupa CTA tegas.',
            'Contoh: Diskon 40% sepatu lari, hanya sampai Minggu, gratis ongkir'),
        V('musiman', 'Promo Musiman', 'Ramadan, Lebaran, 11.11, Harbolnas, gajian', { adegan: '3', shot: '3', durasi: '10s', style: 'cine', voice: 'Voice-Over Narrator' },
            { 'Gaya iklan': 'Emosional', 'Tujuan iklan': 'Promo / diskon', 'Struktur cerita': 'Storytelling emosional', 'CTA penutup': 'Beli sekarang' },
            'Bangun suasana momen musiman yang disebut user (Ramadan/Lebaran/Natal/Tahun Baru/tanggal kembar/gajian). Pakai dekorasi, warna, dan ritual khas momen itu secara sopan dan sesuai budaya Indonesia. Hubungkan produk dengan kebutuhan momen tersebut lalu tutup dengan penawaran terbatas.',
            'Contoh: Sirup & kue kering untuk menyambut Lebaran, keluarga berkumpul, promo paket hampers'),
        V('properti', 'Properti / Real Estate', 'Walkthrough, fasilitas, gaya hidup', { adegan: '3', shot: '4', durasi: '10s', ratio: '16:9', style: 'cine', voice: 'Voice-Over Narrator', char: '2' },
            { 'Gaya iklan': 'Lifestyle', 'Tujuan iklan': 'Awareness', 'Struktur cerita': 'Demo produk', 'CTA penutup': 'Chat / DM' },
            'Tur properti berurutan: fasad, ruang tamu, dapur, kamar, area luar/fasilitas. Kamera gimbal/drone halus, cahaya alami hangat, ruangan rapi, sertakan momen penghuni menikmati ruang. Tampilkan keunggulan lokasi dan fasilitas sebagai teks singkat.',
            'Contoh: Rumah 2 lantai minimalis di BSD, 3 kamar, taman belakang, dekat tol'),
        V('kuliner', 'Kuliner / Food', 'Makro makanan, uap, tuang saus, menggugah selera', { adegan: '2', shot: '4', durasi: '8s', ratio: '9:16', style: 'asmr', voice: 'No Voice / Visual Only', char: '1' },
            { 'Gaya iklan': 'Sinematik premium', 'Tujuan iklan': 'Penjualan langsung', 'Struktur cerita': 'Demo produk', 'CTA penutup': 'Kunjungi toko' },
            'Food cinematography: close-up makro, uap panas, tetesan/tuangan saus, sizzle di wajan, potongan yang memperlihatkan isi, tangan yang menyajikan. Warna makanan hangat dan jenuh, latar bersih. Akhiri dengan hero shot hidangan utuh dan nama/lokasi tempat.',
            'Contoh: Seblak ceker level 5 pedas, kuah merah mengepul, topping melimpah'),
        V('jasa', 'Jasa & Layanan', 'Klinik, salon, bengkel, kursus, laundry', { adegan: '3', shot: '3', durasi: '10s', style: 'cine', voice: 'Character + Narrator', char: '2' },
            { 'Gaya iklan': 'Lifestyle', 'Tujuan iklan': 'Awareness', 'Struktur cerita': 'Before → After', 'CTA penutup': 'Chat / DM' },
            'Tunjukkan proses layanan, ruang usaha yang bersih, tenaga profesional, dan hasil/perubahan bagi pelanggan. Bangun kepercayaan (rapi, ramah, bersertifikat) tanpa klaim berlebihan atau janji hasil medis. Cantumkan cara booking di akhir.',
            'Contoh: Salon muslimah di Depok, perawatan rambut, ruang privat, booking via WhatsApp'),
        V('launching', 'Peluncuran Produk', 'Teaser, reveal, dan rilis resmi', { adegan: '3', shot: '3', durasi: '10s', style: 'cine', voice: 'Voice-Over Narrator', char: '1' },
            { 'Gaya iklan': 'Sinematik premium', 'Tujuan iklan': 'Peluncuran produk', 'Struktur cerita': 'Storytelling emosional', 'CTA penutup': 'Follow akun' },
            'Struktur teaser: bangun rasa penasaran (siluet, detail sebagian), reveal produk dramatis di adegan tengah, lalu tanggal rilis dan CTA. Gunakan kontras gelap-terang, kamera dolly lambat, dan musik build-up.',
            'Contoh: Peluncuran earbuds baru warna matte hitam, rilis 15 November'),
        V('testimoni', 'Testimoni Pelanggan', 'Gaya UGC, jujur seperti ulasan nyata', { adegan: '2', shot: '4', durasi: '10s', ratio: '9:16', style: 'ugc', voice: 'Character Dialogue / Lip-Sync', char: '1' },
            { 'Gaya iklan': 'Emosional', 'Tujuan iklan': 'Penjualan langsung', 'Struktur cerita': 'Testimoni', 'CTA penutup': 'Follow akun' },
            'Pelanggan bicara langsung ke kamera dengan gaya natural handheld, ekspresi jujur, bahasa sehari-hari, cerita masalah sebelum dan hasil sesudah. Jangan terlalu rapi; kesan otentik lebih penting. Tampilkan produk dipakai di situasi nyata.',
            'Contoh: Ibu rumah tangga cerita blender portable membantu bikin MPASI cepat'),
        V('brand-story', 'Profil Perusahaan / Brand Story', 'B2B, nilai brand, tim, dan proses', { adegan: '4', shot: '3', durasi: '10s', ratio: '16:9', style: 'cine', voice: 'Voice-Over Narrator', char: '3' },
            { 'Gaya iklan': 'Sinematik premium', 'Tujuan iklan': 'Awareness', 'Struktur cerita': 'Storytelling emosional', 'CTA penutup': 'Kunjungi toko' },
            'Narasi profesional tentang asal-usul perusahaan, nilai, tim, proses kerja, dan dampak untuk klien/masyarakat. Visual kantor/pabrik yang rapi, tim yang berkolaborasi, dan penutup berupa logo serta tagline. Nada kredibel dan hangat, bukan hard sell.',
            'Contoh: Profil CV pengrajin furnitur jati Jepara, ekspor ke 5 negara'),
    ],
    'affiliate': [
        V('review', 'Review Jujur UGC', 'Ulasan natural ala pembeli sungguhan', { adegan: '2', shot: '4', durasi: '10s', ratio: '9:16', style: 'ugc', voice: 'Character + Narrator', char: '1' },
            { 'Gaya konten': 'Review jujur UGC', 'Pembawa konten': 'Creator di depan kamera', 'CTA': 'Klik keranjang kuning' },
            'Gaya review jujur: sebut kelebihan nyata dan satu kekurangan kecil yang wajar. Creator memegang dan memakai produk, tidak membaca naskah kaku. Produk terlihat jelas dan label terbaca.',
            'Contoh: Review serum wajah untuk kulit berminyak setelah 2 minggu pakai'),
        V('unboxing', 'Unboxing', 'Buka paket, kesan pertama, isi kotak', { adegan: '2', shot: '4', durasi: '10s', ratio: '9:16', style: 'ugc', voice: 'Character Dialogue / Lip-Sync', char: '1' },
            { 'Gaya konten': 'Unboxing', 'Pembawa konten': 'Tangan saja (faceless)', 'CTA': 'Cek link di bio' },
            'Urutan unboxing: paket tiba, buka segel, isi kotak satu per satu, kesan pertama, detail kualitas. Kamera top-down dan close-up tangan, suara kertas/plastik yang memuaskan.',
            'Contoh: Unboxing sepatu sneakers putih dari Shopee, cek kualitas jahitan'),
        V('demo', 'Demo Penggunaan', 'Cara pakai langkah demi langkah', { adegan: '3', shot: '3', durasi: '10s', style: 'ugc', voice: 'Character + Narrator', char: '1' },
            { 'Gaya konten': 'Demo penggunaan', 'Pembawa konten': 'Creator di depan kamera', 'CTA': 'Checkout sebelum kehabisan' },
            'Tunjukkan 3 langkah pemakaian yang jelas dan mudah ditiru, hasilnya terlihat nyata, dan satu tips praktis. Close-up pada fitur utama saat digunakan.',
            'Contoh: Demo blender portable bikin jus alpukat dalam 1 menit'),
        V('beforeafter', 'Before–After', 'Perbandingan sebelum dan sesudah', { adegan: '2', shot: '4', durasi: '8s', ratio: '9:16', style: 'ugc', voice: 'Voice-Over Narrator', char: '1' },
            { 'Gaya konten': 'Before–After', 'Pembawa konten': 'Voice-over + B-roll', 'CTA': 'Klik keranjang kuning' },
            'Bagian BEFORE dan AFTER dengan sudut kamera, pencahayaan, dan posisi sama persis agar adil. Tunjukkan hasil realistis tanpa klaim berlebihan atau janji instan.',
            'Contoh: Pembersih noda sepatu, sebelum dan sesudah dalam 3 menit'),
        V('banding', 'Perbandingan Produk', 'Fitur dan harga dibanding alternatif', { adegan: '3', shot: '3', durasi: '10s', style: 'cine', voice: 'Voice-Over Narrator', char: '1' },
            { 'Gaya konten': 'Perbandingan fitur', 'Pembawa konten': 'Voice-over + B-roll', 'CTA': 'Cek link di bio' },
            'Bandingkan secara adil 2-3 kriteria (harga, fitur, daya tahan) dengan visual berdampingan. Gunakan produk generik untuk pembanding tanpa menyebut merek pesaing yang bisa menimbulkan masalah hukum.',
            'Contoh: Power bank 20.000 mAh versus power bank biasa, kecepatan charge'),
        V('top3', 'Rekomendasi Top 3 / Haul', 'Daftar produk pilihan dalam satu video', { adegan: '3', shot: '3', durasi: '8s', ratio: '9:16', style: 'ugc', voice: 'Character + Narrator', char: '1' },
            { 'Gaya konten': 'Demo penggunaan', 'Pembawa konten': 'Creator di depan kamera', 'CTA': 'Cek link di bio' },
            'Satu adegan per produk pilihan, masing-masing dengan alasan singkat dan kisaran harga. Transisi cepat antar produk, urutan dari kejutan ke favorit utama.',
            'Contoh: 3 alat dapur murah di bawah 100 ribu untuk anak kos'),
        V('flashsale', 'Flash Sale / Live Teaser', 'Urgensi harga dan stok untuk TikTok Shop', { adegan: '2', shot: '4', durasi: '5s', ratio: '9:16', style: 'cine', voice: 'Voice-Over Narrator', char: '1' },
            { 'Gaya konten': 'Problem → Solution', 'Marketplace': 'TikTok Shop', 'CTA': 'Checkout sebelum kehabisan' },
            'Hook sangat cepat dengan harga coret dan potongan, hitung mundur, dan indikator stok menipis. Total durasi pendek dan padat; produk dan harga harus terbaca jelas.',
            'Contoh: Flash sale mukena travel, diskon 50%, hanya 100 pcs'),
    ],
    'fakta-unik': [
        V('sains', 'Sains & Alam', 'Fenomena alam dan penjelasan ilmiah', { adegan: '3', shot: '3', durasi: '10s', style: 'doc', voice: 'Voice-Over Narrator', char: '1' },
            { 'Kategori fakta': 'Sains & alam', 'Visual dominan': 'Macro & sinematik', 'Gaya narasi': 'Santai & penasaran' }, 'Fakta harus akurat dan bisa diverifikasi. Gunakan visual makro dan analogi sederhana untuk menjelaskan sebab-akibat.', 'Contoh: Kenapa langit berwarna biru dan senja berwarna merah'),
        V('hewan', 'Hewan', 'Fakta menakjubkan dunia satwa', { adegan: '3', shot: '3', durasi: '10s', style: 'doc', voice: 'Voice-Over Narrator', char: '1' },
            { 'Kategori fakta': 'Hewan', 'Visual dominan': 'Footage dokumenter', 'Gaya narasi': 'Santai & penasaran' }, 'Gaya dokumenter alam: habitat nyata, perilaku khas hewan, close-up detail tubuh. Hindari antropomorfisme kecuali diminta.', 'Contoh: Gurita punya tiga jantung dan darah biru'),
        V('tubuh', 'Tubuh Manusia', 'Biologi dan kesehatan umum', { adegan: '3', shot: '3', durasi: '10s', style: 'doc', voice: 'Voice-Over Narrator', char: '1' },
            { 'Kategori fakta': 'Tubuh manusia', 'Visual dominan': 'Rekonstruksi 3D', 'Gaya narasi': 'Serius edukatif' }, 'Visual 3D/anatomi bersih dan tidak vulgar. Informasi bersifat edukasi umum, jangan memberi diagnosis atau saran medis.', 'Contoh: Kenapa kita menguap dan bisa menular'),
        V('antariksa', 'Antariksa', 'Planet, bintang, dan alam semesta', { adegan: '3', shot: '3', durasi: '10s', style: 'cine', voice: 'Voice-Over Narrator', char: '1' },
            { 'Kategori fakta': 'Antariksa', 'Visual dominan': 'Rekonstruksi 3D', 'Gaya narasi': 'Dramatis' }, 'Visual kosmik epik dengan skala yang terasa: bandingkan ukuran, jarak, dan waktu dengan hal yang dikenal sehari-hari.', 'Contoh: Sehari di Venus lebih panjang daripada setahunnya'),
        V('budaya', 'Sejarah & Budaya Indonesia', 'Cerita nusantara yang jarang diketahui', { adegan: '3', shot: '3', durasi: '10s', style: 'Nature, warm, documentary', voice: 'Voice-Over Narrator', char: '2' },
            { 'Kategori fakta': 'Budaya & Indonesia', 'Visual dominan': 'Footage dokumenter', 'Gaya narasi': 'Santai & penasaran' }, 'Hormati budaya dan sejarah; hindari klaim yang diperdebatkan tanpa menyebut bahwa ada versi lain. Visual rekonstruksi periode dengan detail busana dan arsitektur yang tepat.', 'Contoh: Borobudur pernah terkubur abu vulkanik berabad-abad'),
        V('teknologi', 'Teknologi & Psikologi', 'Cara kerja teknologi dan perilaku manusia', { adegan: '3', shot: '3', durasi: '10s', style: 'doc', voice: 'Voice-Over Narrator', char: '1' },
            { 'Kategori fakta': 'Teknologi', 'Visual dominan': 'Infografis animasi', 'Gaya narasi': 'Santai & penasaran' }, 'Infografis animasi bersih dengan teks angka besar; jelaskan konsep rumit dengan analogi.', 'Contoh: Kenapa baterai ponsel cepat menurun saat dingin'),
        V('mitos', 'Mitos vs Fakta', 'Bongkar kesalahpahaman umum', { adegan: '3', shot: '3', durasi: '8s', ratio: '9:16', style: 'doc', voice: 'Voice-Over Narrator', char: '1' },
            { 'Jumlah fakta': '3 fakta', 'Tingkat kejutan': 'Sangat mengejutkan', 'Gaya narasi': 'Dramatis' }, 'Struktur berulang: sebut MITOS populer lalu bongkar dengan FAKTA. Tampilkan label MITOS/FAKTA di layar. Jangan menyebut mitos tanpa koreksi yang jelas.', 'Contoh: Mitos makan malam bikin gemuk dan fakta sebenarnya'),
    ],
    'objek-bicara': [
        V('curhat', 'Komedi Curhat', 'Objek mengeluh dengan lucu', { adegan: '2', shot: '3', durasi: '8s', ratio: '9:16', style: 'pixar', voice: 'Character Dialogue / Lip-Sync' },
            { 'Kepribadian objek': 'Cerewet lucu', 'Tema konten': 'Curhat', 'Format': 'Monolog ke kamera' }, 'Monolog komedi dengan punchline kuat di akhir. Ekspresi wajah objek berlebihan dan jelas. Bahasa gaul sehari-hari yang relatable.', 'Contoh: Sandal jepit curhat selalu ditinggal di depan masjid'),
        V('edukasi', 'Edukasi Fun', 'Belajar lewat objek yang mengajar', { adegan: '3', shot: '3', durasi: '10s', style: 'pixar', voice: 'Character Dialogue / Lip-Sync' },
            { 'Kepribadian objek': 'Bijak', 'Tema konten': 'Edukasi', 'Format': 'Monolog ke kamera' }, 'Objek menjelaskan satu konsep sederhana dengan contoh visual. Akhiri dengan ringkasan satu kalimat yang mudah diingat.', 'Contoh: Sikat gigi mengajarkan cara menyikat gigi yang benar'),
        V('promosi', 'Promosi Halus Produk', 'Produk sendiri sebagai karakter', { adegan: '2', shot: '3', durasi: '10s', style: 'pixar', voice: 'Character Dialogue / Lip-Sync' },
            { 'Kepribadian objek': 'Polos imut', 'Tema konten': 'Promosi halus', 'Format': 'Monolog ke kamera' }, 'Produk berbicara tentang manfaatnya secara menghibur tanpa terdengar menjual keras. Bentuk, warna, dan label produk wajib sama dengan referensi. CTA lembut di penutup.', 'Contoh: Botol minum bicara soal ingatkan pemiliknya minum air'),
        V('dialog', 'Dialog Antar Objek', 'Dua objek atau lebih berdebat', { adegan: '3', shot: '3', durasi: '10s', style: 'pixar', voice: 'Character Dialogue / Lip-Sync', char: '3' },
            { 'Kepribadian objek': 'Sinis sarkas', 'Tema konten': 'Komedi', 'Format': 'Dialog antar objek' }, 'Setiap objek punya kepribadian dan gaya bicara berbeda. Dialog bergantian jelas, tentukan siapa bicara di setiap shot untuk lip-sync.', 'Contoh: Remote TV dan sofa berdebat soal siapa yang paling dicari'),
        V('podcast', 'Wawancara / Podcast Objek', 'Format talk show dengan objek', { adegan: '3', shot: '3', durasi: '10s', ratio: '16:9', style: 'pixar', voice: 'Character Dialogue / Lip-Sync', char: '2' },
            { 'Format': 'Wawancara / podcast', 'Tema konten': 'Edukasi', 'Kepribadian objek': 'Dramatis lebay' }, 'Set studio podcast mini: dua kursi, mikrofon, pencahayaan hangat. Pewawancara dan narasumber bergantian, ada reaksi dan potongan close-up.', 'Contoh: Wawancara eksklusif dengan sendok yang sering hilang'),
        V('motivasi', 'Motivasi', 'Pesan positif dari benda sehari-hari', { adegan: '2', shot: '3', durasi: '10s', style: 'drama', voice: 'Character Dialogue / Lip-Sync' },
            { 'Kepribadian objek': 'Bijak', 'Tema konten': 'Motivasi', 'Format': 'Monolog ke kamera' }, 'Pesan singkat menyentuh dengan musik lembut. Hindari menggurui; gunakan metafora dari fungsi objek.', 'Contoh: Payung tua bicara soal tetap setia saat hujan'),
    ],
    'drama-pendek': [
        V('keluarga', 'Keluarga Haru', 'Cerita hangat dan menyentuh', { adegan: '3', shot: '3', durasi: '15s', style: 'drama' },
            { 'Genre': 'Keluarga', 'Emosi utama': 'Haru', 'Ending': 'Sad', 'Latar budaya': 'Indonesia modern' }, 'Emosi dibangun lewat detail kecil (benda kenangan, tatapan, jeda). Dialog pendek dan natural, tanpa melodrama berlebihan.', 'Contoh: Anak merantau pulang menemukan surat terakhir ibunya'),
        V('romantis', 'Romantis', 'Pertemuan, rindu, dan kejutan manis', { adegan: '3', shot: '3', durasi: '15s', style: 'drama' },
            { 'Genre': 'Romantis', 'Emosi utama': 'Rindu', 'Ending': 'Happy', 'Latar budaya': 'Kota urban' }, 'Chemistry lewat bahasa tubuh dan tatapan. Pencahayaan hangat, kamera dekat dan lembut.', 'Contoh: Dua orang asing bertukar payung di halte hujan'),
        V('horor', 'Horor Kampung', 'Ketegangan dan atmosfer mistis', { adegan: '3', shot: '4', durasi: '10s', style: 'Dark, moody, dramatic' },
            { 'Genre': 'Horor', 'Emosi utama': 'Takut', 'Plot twist': 'Ya, di akhir', 'Ending': 'Menggantung (cliffhanger)', 'Latar budaya': 'Kampung / desa' }, 'Bangun ketakutan lewat suara, bayangan, dan hal yang tidak terlihat; hindari gore. Tidak ada adegan kekerasan grafis. Jump scare hanya sekali di puncak.', 'Contoh: Penjaga pos ronda mendengar langkah kaki di sawah tengah malam'),
        V('thriller', 'Thriller Misteri', 'Teka-teki dan ketegangan', { adegan: '3', shot: '4', durasi: '10s', style: 'Dark, moody, dramatic' },
            { 'Genre': 'Thriller', 'Emosi utama': 'Tegang', 'Plot twist': 'Ya, di akhir', 'Ending': 'Terbuka', 'Latar budaya': 'Kota urban' }, 'Tebar petunjuk visual yang baru masuk akal di twist akhir. Tempo makin cepat menjelang klimaks.', 'Contoh: Kurir paket menemukan alamat tujuan yang tidak pernah ada'),
        V('komedi', 'Komedi Situasi', 'Kesalahpahaman lucu sehari-hari', { adegan: '3', shot: '3', durasi: '10s', ratio: '9:16', style: 'cine', voice: 'Character Dialogue / Lip-Sync' },
            { 'Genre': 'Komedi', 'Emosi utama': 'Lucu', 'Plot twist': 'Ya, di akhir', 'Ending': 'Happy', 'Latar budaya': 'Kantor' }, 'Setup, eskalasi, punchline. Timing komedi lewat jeda dan reaksi wajah. Dialog ringan dan relatable.', 'Contoh: Salah kirim chat ke grup kantor padahal ingin ke pacar'),
        V('inspiratif', 'Inspiratif & Perjuangan', 'Bangkit dari kesulitan', { adegan: '3', shot: '3', durasi: '15s', style: 'drama' },
            { 'Genre': 'Inspiratif', 'Emosi utama': 'Haru', 'Ending': 'Happy', 'Latar budaya': 'Kampung / desa' }, 'Tunjukkan proses dan usaha berulang, bukan hanya hasil. Momen titik terendah sebelum kebangkitan harus terasa jujur.', 'Contoh: Penjual gorengan keliling yang akhirnya punya kedai sendiri'),
        V('sekolah', 'Sekolah & Persahabatan', 'Kisah remaja dan kampus', { adegan: '3', shot: '3', durasi: '10s', ratio: '9:16', style: 'cine', voice: 'Character Dialogue / Lip-Sync' },
            { 'Genre': 'Persahabatan', 'Emosi utama': 'Haru', 'Ending': 'Happy', 'Latar budaya': 'Sekolah / kampus' }, 'Tokoh remaja/dewasa muda dengan bahasa gaul wajar. Aman untuk semua umur, tanpa konten dewasa.', 'Contoh: Tiga sahabat berbagi bekal terakhir sebelum kelulusan'),
    ],
    'timelapse': [
        V('konstruksi', 'Konstruksi Bangunan', 'Dari pondasi sampai selesai', { adegan: '3', shot: '2', durasi: '10s', ratio: '16:9', style: 'tl' },
            { 'Jenis timelapse': 'Konstruksi bangunan', 'Gerak kamera': 'Statis tripod', 'Kecepatan': 'Cepat' }, 'Kamera terkunci pada sudut yang sama; tampilkan tahap pondasi, struktur, dinding, atap, finishing, lalu reveal akhir.', 'Contoh: Rumah kayu kecil dibangun di tepi danau'),
        V('renovasi', 'Renovasi Ruangan', 'Transformasi interior', { adegan: '3', shot: '2', durasi: '10s', style: 'tl' },
            { 'Jenis timelapse': 'Renovasi ruangan', 'Gerak kamera': 'Statis tripod', 'Musik': 'Upbeat' }, 'Sudut kamera tetap; perabot berpindah, cat berubah, dekorasi ditambah. Reveal akhir dengan pencahayaan terbaik.', 'Contoh: Kamar kos sempit disulap jadi studio kreator'),
        V('kota', 'Kota & Langit', 'Siang ke malam, lalu lintas, cuaca', { adegan: '3', shot: '2', durasi: '10s', ratio: '16:9', style: 'tl' },
            { 'Jenis timelapse': 'Siang → malam', 'Gerak kamera': 'Slow push-in halus', 'Musik': 'Cinematic build-up' }, 'Transisi cahaya golden hour ke blue hour, lampu kota menyala bertahap, jejak lampu kendaraan.', 'Contoh: Skyline Jakarta dari senja sampai malam'),
        V('tumbuhan', 'Tumbuhan & Bunga', 'Tumbuh, mekar, dan berbuah', { adegan: '3', shot: '2', durasi: '10s', style: 'asmr' },
            { 'Jenis timelapse': 'Bunga mekar', 'Gerak kamera': 'Statis tripod', 'Musik': 'Ambient' }, 'Makro, latar gelap atau cahaya studio lembut, tahap tumbuh yang jelas dari biji hingga mekar.', 'Contoh: Benih bunga matahari tumbuh dan mekar di jendela'),
        V('memasak', 'Proses Memasak', 'Dari bahan mentah ke hidangan jadi', { adegan: '3', shot: '2', durasi: '10s', ratio: '9:16', style: 'asmr' },
            { 'Jenis timelapse': 'Proses memasak', 'Gerak kamera': 'Statis tripod', 'Musik': 'Upbeat' }, 'Kamera top-down tetap; bahan bertambah dan berubah warna/tekstur hingga hidangan disajikan.', 'Contoh: Membuat rendang dari awal sampai matang'),
        V('seni', 'Melukis & Seni', 'Proses kreatif sampai karya jadi', { adegan: '3', shot: '2', durasi: '10s', style: 'tl' },
            { 'Jenis timelapse': 'Melukis / seni', 'Gerak kamera': 'Statis tripod', 'Musik': 'Ambient' }, 'Tangan seniman dan kanvas dari sudut tetap, karya terbentuk bertahap, akhiri dengan karya utuh di dinding.', 'Contoh: Mural bunga di tembok kafe dari sketsa sampai selesai'),
    ],
    'asmr': [
        V('slicing', 'Slicing & Cutting', 'Memotong objek satisfying', { adegan: '2', shot: '3', durasi: '15s', ratio: '9:16', style: 'asmr' },
            { 'Trigger utama': 'Memotong / slicing', 'Intensitas': 'Tajam & renyah', 'Tangan': 'Tangan saja' }, 'Close-up pisau tipis, potongan bersih, cross-section yang rapi, pencahayaan studio lembut tanpa bayangan keras.', 'Contoh: Memotong sabun pastel di atas meja marmer'),
        V('tapping', 'Tapping & Scratching', 'Ketukan dan gesekan tekstur', { adegan: '2', shot: '3', durasi: '15s', style: 'asmr' },
            { 'Trigger utama': 'Tapping', 'Intensitas': 'Lembut', 'Mikrofon': 'Binaural 3D' }, 'Kuku/jari pada permukaan berbeda (kaca, kayu, plastik), tempo ritmis, mikrofon dekat.', 'Contoh: Mengetuk berbagai botol kosmetik bergantian'),
        V('crunch', 'Kuliner Crunch', 'Makanan renyah dan menggugah', { adegan: '2', shot: '3', durasi: '10s', ratio: '9:16', style: 'asmr' },
            { 'Trigger utama': 'Crunch renyah', 'Intensitas': 'Tajam & renyah', 'Tangan': 'Tangan saja' }, 'Close-up gigitan dan retakan, remah jatuh, suara renyah jelas. Makanan tampak segar dan menggoda.', 'Contoh: Menggigit keripik kentang tebal rasa balado'),
        V('cairan', 'Menuang & Cairan', 'Menuang, menetes, mengalir', { adegan: '2', shot: '3', durasi: '15s', style: 'asmr' },
            { 'Trigger utama': 'Menuang cairan', 'Intensitas': 'Sedang', 'Mikrofon': 'Stereo' }, 'Slow motion cairan, riak, gelembung, cahaya tembus cairan. Latar bersih dan warna pastel.', 'Contoh: Menuang sirup madu ke atas pancake'),
        V('keyboard', 'Keyboard & Mengetik', 'Switch mekanikal dan desk setup', { adegan: '2', shot: '3', durasi: '15s', style: 'asmr' },
            { 'Trigger utama': 'Mengetik / keyboard', 'Intensitas': 'Sedang', 'Mikrofon': 'Mono dekat' }, 'Close-up keycap, switch bergerak, desk setup rapi dengan lampu RGB lembut.', 'Contoh: Mengetik di keyboard mekanik switch creamy dalam kamar gelap'),
        V('slime', 'Squishy & Slime', 'Tekstur lembut yang memuaskan', { adegan: '2', shot: '3', durasi: '15s', style: 'asmr' },
            { 'Trigger utama': 'Squishing / slime', 'Intensitas': 'Lembut', 'Whisper': 'Tidak' }, 'Close-up tekstur menggembung dan meregang, warna cerah, gerakan tangan perlahan.', 'Contoh: Menekan slime glitter warna ungu di wadah kaca'),
        V('skincare', 'Skincare ASMR', 'Produk perawatan kulit, komersial', { adegan: '2', shot: '3', durasi: '15s', ratio: '9:16', style: 'asmr' },
            { 'Trigger utama': 'Menuang cairan', 'Intensitas': 'Lembut', 'Whisper': 'Ya, bisik pendek' }, 'Tekstur krim/serum, tetesan, tutup botol dibuka, tangan mengaplikasikan. Label dan kemasan produk harus terlihat jelas dan akurat; tanpa klaim medis.', 'Contoh: Serum vitamin C dalam botol amber, tekstur gel bening'),
    ],

    'animasi-cerita': [
        V('petualangan', 'Petualangan', 'Kisah perjalanan dan eksplorasi', { adegan: '3', shot: '3', durasi: '10s', style: 'pixar', voice: 'Character Dialogue / Lip-Sync', char: '2' },
            { 'Genre': 'Petualangan', 'Target usia': 'Semua umur', 'Tema / pesan moral': 'Keberanian mencoba' },
            'Gaya animasi konsisten (Anime 2D / 3D Pixar / Motion graphic sesuai pilihan). Karakter ekspresif, gerakan squash-stretch, latar berwarna. Struktur setup → tantangan → resolusi.',
            'Contoh: Rubah kecil mencari bintang jatuh di hutan malam'),
        V('komedi', 'Komedi Animasi', 'Humor visual dan gagal lucu', { adegan: '3', shot: '3', durasi: '8s', ratio: '9:16', style: 'pixar', voice: 'Character Dialogue / Lip-Sync' },
            { 'Genre': 'Komedi', 'Target usia': 'Semua umur' },
            'Timing komedi visual, ekspresi berlebihan, punchline di shot terakhir. Dialog singkat dan relatable.',
            'Contoh: Kucing gagal melompat ke meja dapur berulang kali'),
        V('edukasi', 'Edukasi Anak', 'Belajar lewat cerita animasi', { adegan: '3', shot: '3', durasi: '10s', style: 'pixar', voice: 'Character + Narrator', char: '2' },
            { 'Genre': 'Edukasi', 'Target usia': 'Anak (4-9)', 'Tema / pesan moral': 'Berbagi' },
            'Bahasa sederhana, pesan moral jelas di penutup, warna cerah aman untuk anak. Hindari konten menakutkan.',
            'Contoh: Lebah mengajarkan pentingnya kerja sama di sarang'),
        V('fantasi', 'Fantasi & Dongeng', 'Dunia ajaib dan makhluk mitos', { adegan: '3', shot: '3', durasi: '12s', style: 'pixar', voice: 'Character Dialogue / Lip-Sync', char: '2' },
            { 'Genre': 'Fantasi', 'Target usia': 'Remaja' },
            'Palet magis, lighting dramatis, creature design konsisten. Hook visual kuat di 2 detik pertama.',
            'Contoh: Naga mini belajar terbang di atas desa awan'),
        V('horor-ringan', 'Horor Ringan', 'Ketegangan ramah tanpa gore', { adegan: '3', shot: '3', durasi: '10s', style: 'Dark, moody, dramatic', voice: 'Character Dialogue / Lip-Sync' },
            { 'Genre': 'Horor ringan', 'Target usia': 'Remaja' },
            'Bangun tegang lewat bayangan dan suara, tanpa kekerasan grafis. Twist ringan di akhir.',
            'Contoh: Boneka di loteng bergerak sendiri saat hujan'),
    ],
    'podcast': [
        V('talkshow', 'Talk Show / Wawancara', 'Host dan tamu di studio', { adegan: '3', shot: '3', durasi: '15s', ratio: '16:9', style: 'cine', voice: 'Character Dialogue / Lip-Sync', char: '2' },
            { 'Format podcast': 'Wawancara', 'Jumlah pembicara': 'Host + 1 tamu', 'Topik': 'Lifestyle' },
            'Set studio hangat, mikrofon terlihat, reaction shot, dialog bergantian jelas untuk lip-sync. Intro topik → insight → CTA episode.',
            'Contoh: Host wawancara founder UMKM kopi lokal'),
        V('solo', 'Solo Host / Monolog', 'Satu host bicara ke kamera', { adegan: '2', shot: '4', durasi: '12s', ratio: '9:16', style: 'ugc', voice: 'Character Dialogue / Lip-Sync', char: '1' },
            { 'Format podcast': 'Solo host', 'Jumlah pembicara': '1 host', 'Topik': 'Motivasi' },
            'Host menghadap kamera, B-roll pendukung minimal, hook pertanyaan di awal, CTA follow di akhir.',
            'Contoh: Host bahas 3 kebiasaan pagi yang mengubah hidup'),
        V('debat', 'Debat / Diskusi', 'Dua sudut pandang beradu argumen', { adegan: '3', shot: '3', durasi: '15s', ratio: '16:9', style: 'cine', voice: 'Character Dialogue / Lip-Sync', char: '3' },
            { 'Format podcast': 'Debat', 'Jumlah pembicara': 'Host + 2 tamu', 'Topik': 'Sosial' },
            'Setiap pembicara punya posisi jelas. Potong ke yang sedang bicara; reaction dari lawan. Host menengahi di penutup.',
            'Contoh: Debat singkat WFH vs kantor'),
        V('story', 'Storytelling Podcast', 'Narasi cerita dengan visual pendukung', { adegan: '3', shot: '3', durasi: '15s', style: 'drama', voice: 'Voice-Over Narrator', char: '1' },
            { 'Format podcast': 'Storytelling', 'Jumlah pembicara': '1 narator', 'Topik': 'Kisah nyata' },
            'Narator VO + B-roll sinematik yang mengilustrasikan cerita. Emosi naik pelan menuju klimaks.',
            'Contoh: Kisah kurir yang menemukan dompet berisi surat wasiat'),
        V('clip', 'Highlight Clip', 'Potongan viral dari episode panjang', { adegan: '2', shot: '3', durasi: '8s', ratio: '9:16', style: 'ugc', voice: 'Character Dialogue / Lip-Sync', char: '2' },
            { 'Format podcast': 'Highlight clip', 'Jumlah pembicara': 'Host + 1 tamu', 'Topik': 'Bisnis' },
            'Langsung ke momen paling kuat (quote / punchline). Teks kutipan di layar opsional. CTA: tonton full episode.',
            'Contoh: Kutipan terbaik tamu soal gagal 5 kali sebelum sukses'),
    ],
    'konten-kreatif': [
        V('skit', 'Skit Komedi', 'Adegan lucu pendek dengan punchline', { adegan: '3', shot: '3', durasi: '10s', ratio: '9:16', style: 'ugc', voice: 'Character Dialogue / Lip-Sync', char: '2' },
            { 'Jenis konten kreatif': 'Skit komedi', 'Nada': 'Lucu / absurd', 'CTA penutup': 'Follow akun' },
            'Setup situasi relate → eskalasi lucu → punchline tak terduga di adegan terakhir. Ekspresi berlebihan boleh, timing komedi penting (jeda sebelum punchline). Dialog pendek, natural, mudah diingat.',
            'Contoh: Skit kucing jadi bos di kantor, menolak kerja lembur'),
        V('tren', 'Tren / Challenge', 'Ikuti format tren yang sedang viral', { adegan: '2', shot: '4', durasi: '8s', ratio: '9:16', style: 'ugc', voice: 'Character + Narrator', char: '1' },
            { 'Jenis konten kreatif': 'Tren / challenge', 'Nada': 'Energik', 'CTA penutup': 'Ajak duet/ikut tren' },
            'Ikuti pola tren yang disebut user (transisi, gerakan, format audio) secara persis, tambahkan sentuhan personal/brand di detail visual. Ritme cepat, transisi di beat yang jelas.',
            'Contoh: Transisi outfit ganti 3x mengikuti beat musik, tema kerja vs santai'),
        V('visual-art', 'Visual Art / Eksperimen', 'Eksplorasi visual artistik & estetik', { adegan: '2', shot: '3', durasi: '10s', ratio: '16:9', style: 'cine', voice: 'No Voice / Visual Only', char: '1' },
            { 'Jenis konten kreatif': 'Visual art / eksperimen', 'Nada': 'Estetik / kontemplatif', 'CTA penutup': 'Follow akun' },
            'Fokus pada komposisi, warna, tekstur, dan gerak kamera artistik. Tanpa dialog; musik/ambience membawa mood. Setiap shot adalah "frame" yang berdiri sendiri secara visual namun tetap satu kesatuan tema.',
            'Contoh: Eksplorasi cahaya pagi menembus tirai, debu melayang, mood tenang'),
        V('stopmotion', 'Gaya Stop-Motion', 'Objek bergerak patah-patah artistik', { adegan: '2', shot: '4', durasi: '8s', ratio: '1:1', style: 'pixar', voice: 'No Voice / Visual Only', char: '1' },
            { 'Jenis konten kreatif': 'Gaya stop-motion', 'Nada': 'Playful', 'CTA penutup': 'Follow akun' },
            'Gerak objek terasa patah-patah khas stop-motion (frame-by-frame feel), objek kecil/mainan/bahan kerajinan sebagai aktor utama. Pencahayaan studio mini, latar minimalis, musik playful.',
            'Contoh: Mainan kayu kecil "berjalan" menyusun menara balok'),
        V('eksperimen-ide', 'Ide Orisinal Bebas', 'Konsep bebas sesuai imajinasi user', { adegan: '3', shot: '3', durasi: '10s', style: 'cine', voice: 'Voice-Over Narrator', char: '1' },
            { 'Jenis konten kreatif': 'Ide orisinal bebas', 'Nada': 'Sesuai ide', 'CTA penutup': 'Follow akun' },
            'Ikuti ide user apa adanya tanpa dipaksa ke format baku; kembangkan jadi storyboard yang koheren dengan hook kuat dan penutup yang memorable.',
            'Contoh: Sehari dalam hidup secangkir kopi, dari biji hingga diminum, sudut pandang orang pertama si kopi'),
    ],

};
